//--------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------------------

namespace BP.AutoNotify.SourceGenerator.Tests
{
    internal partial class Test_001: System.ComponentModel.INotifyPropertyChanged
    {
        [System.CodeDom.Compiler.GeneratedCode("BP.AutoNotify.SourceGenerator.AutoNotifyGenerator", "1.0.0.0"]
        event PropertyChangedEventHandler PropertyChanged;

        [System.CodeDom.Compiler.GeneratedCode("BP.AutoNotify.SourceGenerator.AutoNotifyGenerator", "1.0.0.0"]
        public string Test
        {
            get => _test;
            set => SetAndNotify(ref _test, value);
        }

        [System.CodeDom.Compiler.GeneratedCode("BP.AutoNotify.SourceGenerator.AutoNotifyGenerator", "1.0.0.0"]
        private partial void OnTestUpdated(string oldValue, string newValue);

        [System.CodeDom.Compiler.GeneratedCode("BP.AutoNotify.SourceGenerator.AutoNotifyGenerator", "1.0.0.0"]
        private bool SetAndNotify<T>(ref T field, T newValue, [System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
        }

        [System.CodeDom.Compiler.GeneratedCode("BP.AutoNotify.SourceGenerator.AutoNotifyGenerator", "1.0.0.0"]
        private bool UpdateAndNotify<T>(ref T field, T newValue, [System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
        }
    }
}
